[package]
name = "pollub-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Piotr Piech"]
license = "MIT-0"
description = "Thesis template for WEII, Wydział Elektrotechniki i Informatyki, Politechnika Lubelska."
keywords = ["POLLUB", "WEII", "thesis", "university"]
categories = ["thesis"]
compiler = "0.14.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
