[package]
name = "formal-pollub-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Piotr Piech"]
license = "MIT-0"
description = "Master's thesis at Politechnika Lubelska."
keywords = ["Politechnika Lubelska", "POLLUB", "master's thesis", "university"]
categories = ["thesis"]
compiler = "0.14.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
